# Generated by Django 3.1.5 on 2021-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0009_auto_20210209_2050"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="is_booked",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
